on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
   
        #    - name: Login to Amazon ECR
        #      id: login-ecr
        #      uses: aws-actions/amazon-ecr-login@v1
        #
        #    - name: Build, tag, and push image to Amazon ECR
        #      env:
        #        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #        ECR_REPOSITORY: docapp_fe
        #        IMAGE_TAG: latest
        #      run: |
        #        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        #        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        #
        #    - name: Logout of Amazon ECR
        #      if: always()
        #      run: docker logout ${{ steps.login-ecr.outputs.registry }}
        #
    - name: Render Amazon ECS task definition
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: docapp-fe
        image: 050115469000.dkr.ecr.us-west-2.amazonaws.com/docapp_fe:latest

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-web-container.outputs.task-definition }}
        service: docapp-fe
        cluster: DocAppCluster
